when:
  - event: push
  - event: pull_request

labels:
  platform: linux/amd64

steps:
  - name: build
    image: barrywalker71/kickassembler:latest
    commands:
      - java -jar /KickAss.jar main.asm
      - ls -la *.prg *.sym

  - name: test-move-validation
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/move_validation.6502
    depends_on: [build]

  - name: test-comprehensive
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/comprehensive.6502
    depends_on: [build]
