when:
  - event: push
  - event: pull_request

labels:
  platform: linux/amd64

# Full clone needed for cog to access commit history and tags
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      tags: true

steps:
  # Check that commits follow conventional commit format
  - name: check-commits
    image: simbachain/cocogitto:latest
    commands:
      - cog --version
      - cog check --from-latest-tag || cog check || echo "No conventional commits yet - will enforce after initial tag"

  # Determine version and update version.asm BEFORE build
  - name: prepare-version
    image: simbachain/cocogitto:latest
    commands:
      - |
        git config --global --add safe.directory /woodpecker/src

        # Check if bump is needed
        NEW_VERSION=$(cog bump --auto --dry-run 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' || echo "")

        if [ -n "$NEW_VERSION" ]; then
          echo "Version bump needed: $NEW_VERSION"
          chmod +x scripts/update-version.sh
          ./scripts/update-version.sh "$NEW_VERSION"
          echo "version.asm updated:"
          cat version.asm
          # Save version for release step
          echo "$NEW_VERSION" > .new_version
          # Generate changelog for release notes
          echo "Generating changelog..."
          cog changelog --at "$NEW_VERSION" > .changelog 2>/dev/null || echo "Release $NEW_VERSION" > .changelog
          cat .changelog
        else
          echo "No version bump needed"
        fi
    depends_on: [check-commits]

  - name: build
    image: barrywalker71/kickassembler:latest
    commands:
      - java -jar /KickAss.jar main.asm
      - ls -la *.prg *.sym *.d64
      - echo "Build artifacts:"
      - cat version.asm | head -10
    depends_on: [prepare-version]

  - name: test-move-validation
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/move_validation.6502
    depends_on: [build]

  - name: test-comprehensive
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/comprehensive.6502
    depends_on: [build]

  # Create tag and release after tests pass (main only)
  - name: release
    image: alpine/git
    commands:
      - |
        apk add --no-cache curl jq

        # Check if we have a new version to release
        if [ ! -f .new_version ]; then
          echo "No version bump needed, skipping release"
          exit 0
        fi

        NEW_VERSION=$(cat .new_version)
        echo "Creating release for version $NEW_VERSION"

        # Configure git with token auth via netrc
        git config --global user.email "ci@woodpecker.local"
        git config --global user.name "Woodpecker CI"
        git config --global --add safe.directory /woodpecker/src
        echo "machine github.com login x-access-token password $GITHUB_TOKEN" > ~/.netrc
        chmod 600 ~/.netrc

        # Create and push tag
        git tag -a "$NEW_VERSION" -m "Release $NEW_VERSION"
        git push https://github.com/${CI_REPO}.git "$NEW_VERSION"

        echo "Creating release via GitHub API..."

        # Read changelog and build release body
        CHANGELOG=$(cat .changelog 2>/dev/null || echo "")
        RELEASE_BODY=$(printf "## C64 Chess %s\n\n%s\n\n---\n**Downloads:**\n- C64Chess.d64 - Disk image\n- main.prg - Raw PRG file" "$NEW_VERSION" "$CHANGELOG")

        # Create the release on GitHub
        RELEASE_RESPONSE=$(curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/$CI_REPO/releases" \
          -d "$(jq -n --arg tag "$NEW_VERSION" --arg name "C64 Chess $NEW_VERSION" --arg body "$RELEASE_BODY" '{tag_name: $tag, name: $name, body: $body}')")

        RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
        echo "Created release ID: $RELEASE_ID"

        if [ "$RELEASE_ID" = "null" ]; then
          echo "Failed to create release:"
          echo "$RELEASE_RESPONSE"
          exit 1
        fi

        # Upload artifacts to GitHub
        for FILE in C64Chess.d64 main.prg; do
          if [ -f "$FILE" ]; then
            echo "Uploading $FILE..."
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/$CI_REPO/releases/$RELEASE_ID/assets?name=$FILE" \
              --data-binary "@$FILE"
          fi
        done

        echo "Release $NEW_VERSION created successfully!"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      - event: push
        branch: main
    depends_on: [test-move-validation, test-comprehensive]
