when:
  - event: push
  - event: pull_request

labels:
  platform: linux/amd64

# Full clone needed for cog to access commit history and tags
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      tags: true

steps:
  # Check that commits follow conventional commit format
  - name: check-commits
    image: simbachain/cocogitto:latest
    commands:
      - cog --version
      - cog check --from-latest-tag || cog check || echo "No conventional commits yet - will enforce after initial tag"

  - name: build
    image: barrywalker71/kickassembler:latest
    commands:
      - java -jar /KickAss.jar main.asm
      - ls -la *.prg *.sym *.d64
      - echo "Build artifacts:"
      - cat version.asm | head -10
    depends_on: [check-commits]

  - name: test-move-validation
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/move_validation.6502
    depends_on: [build]

  - name: test-comprehensive
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/comprehensive.6502
    depends_on: [build]

  # Create tag and release after tests pass (master only)
  - name: release
    image: simbachain/cocogitto:latest
    commands:
      - |
        echo "Checking if version bump is needed..."
        git config --global user.email "ci@woodpecker.local"
        git config --global user.name "Woodpecker CI"
        git config --global --add safe.directory /woodpecker/src

        # Check if bump is needed
        NEW_VERSION=$(cog bump --auto --dry-run 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' || echo "")
        if [ -z "$NEW_VERSION" ]; then
          echo "No version bump needed"
          exit 0
        fi

        echo "Creating tag $NEW_VERSION..."
        cog bump --auto

        echo "Pushing tag..."
        git push origin "$NEW_VERSION"

        echo "Generating changelog..."
        CHANGELOG=$(cog changelog --at "$NEW_VERSION" 2>/dev/null || echo "Release $NEW_VERSION")

        echo "Creating release via GitHub API..."
        RELEASE_BODY=$(cat <<EOF
        ## C64 Chess $NEW_VERSION

        $CHANGELOG

        ---
        Download the D64 disk image and load it in your favorite C64 emulator!

        **Files:**
        - \`C64Chess.d64\` - Disk image (use with VICE or real hardware)
        - \`main.prg\` - Raw PRG file
        EOF
        )

        # Create the release on GitHub
        RELEASE_RESPONSE=$(curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${CI_REPO}/releases" \
          -d "{\"tag_name\": \"$NEW_VERSION\", \"name\": \"C64 Chess $NEW_VERSION\", \"body\": $(echo "$RELEASE_BODY" | jq -Rs .)}")

        RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id')
        UPLOAD_URL=$(echo "$RELEASE_RESPONSE" | jq -r '.upload_url' | sed 's/{?name,label}//')
        echo "Created release ID: $RELEASE_ID"

        # Upload artifacts to GitHub
        for FILE in C64Chess.d64 main.prg; do
          if [ -f "$FILE" ]; then
            echo "Uploading $FILE..."
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              "${UPLOAD_URL}?name=$FILE" \
              --data-binary "@$FILE"
          fi
        done

        echo "Release $NEW_VERSION created successfully!"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      - event: push
        branch: main
    depends_on: [test-move-validation, test-comprehensive]
