when:
  - event: push
  - event: pull_request
  - event: tag

labels:
  platform: linux/amd64

steps:
  # Check that commits follow conventional commit format
  - name: check-commits
    image: simbachain/cocogitto:latest
    commands:
      - cog --version
      - cog check --from-latest-tag || cog check || echo "No conventional commits yet - will enforce after initial tag"
    when:
      - event: push
      - event: pull_request

  # Bump version on master branch pushes (not PRs)
  - name: bump-version
    image: simbachain/cocogitto:latest
    commands:
      - |
        echo "Checking if version bump is needed..."
        # Configure git for cog
        git config --global user.email "ci@woodpecker.local"
        git config --global user.name "Woodpecker CI"
        git config --global --add safe.directory /woodpecker/src
        # Try to bump - if no bumpable commits, it will exit gracefully
        if cog bump --auto --dry-run 2>/dev/null; then
          echo "Version bump detected, running update script..."
          NEW_VERSION=$(cog bump --auto --dry-run 2>&1 | grep -oP '(?<=Bumping to )\d+\.\d+\.\d+' || echo "")
          if [ -n "$NEW_VERSION" ]; then
            echo "New version will be: $NEW_VERSION"
            chmod +x scripts/update-version.sh
            ./scripts/update-version.sh "$NEW_VERSION"
            echo "version.asm updated:"
            cat version.asm
          fi
        else
          echo "No version bump needed"
        fi
    when:
      - event: push
        branch: master
    depends_on: [check-commits]

  - name: build
    image: barrywalker71/kickassembler:latest
    commands:
      - java -jar /KickAss.jar main.asm
      - ls -la *.prg *.sym *.d64
      - echo "Build artifacts:"
      - cat version.asm | head -10
    depends_on: [bump-version]

  - name: test-move-validation
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/move_validation.6502
    depends_on: [build]

  - name: test-comprehensive
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/comprehensive.6502
    depends_on: [build]

  # Create release with d64 artifact on tag push
  - name: release
    image: woodpeckerci/plugin-release:latest
    settings:
      api_key:
        from_secret: gitea_token
      files:
        - "C64Chess.d64"
        - "main.prg"
      title: "C64 Chess ${CI_COMMIT_TAG}"
      note: |
        ## C64 Chess ${CI_COMMIT_TAG}

        Download the D64 disk image and load it in your favorite C64 emulator!

        **Files:**
        - `C64Chess.d64` - Disk image (use with VICE or real hardware)
        - `main.prg` - Raw PRG file
    when:
      - event: tag
    depends_on: [test-move-validation, test-comprehensive]
