when:
  - event: push
  - event: pull_request
  - event: tag

labels:
  platform: linux/amd64

# Full clone needed for cog to access commit history and tags
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      tags: true

steps:
  # Check that commits follow conventional commit format
  - name: check-commits
    image: simbachain/cocogitto:latest
    commands:
      - cog --version
      - cog check --from-latest-tag || cog check || echo "No conventional commits yet - will enforce after initial tag"
    when:
      - event: push
      - event: pull_request

  - name: build
    image: barrywalker71/kickassembler:latest
    commands:
      - java -jar /KickAss.jar main.asm
      - ls -la *.prg *.sym *.d64
      - echo "Build artifacts:"
      - cat version.asm | head -10

  - name: test-move-validation
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/move_validation.6502
    depends_on: [build]

  - name: test-comprehensive
    image: ghcr.io/barryw/sim6502:v3.4.1
    commands:
      - ln -sf $CI_WORKSPACE /code
      - /app/Sim6502TestRunner -s /code/tests/comprehensive.6502
    depends_on: [build]

  # Create tag after tests pass (triggers release pipeline)
  - name: create-tag
    image: simbachain/cocogitto:latest
    commands:
      - |
        echo "Checking if version bump is needed..."
        git config --global user.email "ci@woodpecker.local"
        git config --global user.name "Woodpecker CI"
        git config --global --add safe.directory /woodpecker/src
        # Check if bump is needed
        NEW_VERSION=$(cog bump --auto --dry-run 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' || echo "")
        if [ -n "$NEW_VERSION" ]; then
          echo "Creating tag $NEW_VERSION..."
          # cog bump --auto will: run pre_bump_hooks, commit, create tag
          cog bump --auto
          echo "Pushing tag to trigger release..."
          git push origin "$NEW_VERSION"
        else
          echo "No version bump needed"
        fi
    when:
      - event: push
        branch: master
    depends_on: [test-move-validation, test-comprehensive]

  # Create release with d64 artifact on tag push
  - name: release
    image: woodpeckerci/plugin-release:latest
    settings:
      api_key:
        from_secret: gitea_token
      files:
        - "C64Chess.d64"
        - "main.prg"
      title: "C64 Chess ${CI_COMMIT_TAG}"
      note: |
        ## C64 Chess ${CI_COMMIT_TAG}

        Download the D64 disk image and load it in your favorite C64 emulator!

        **Files:**
        - `C64Chess.d64` - Disk image (use with VICE or real hardware)
        - `main.prg` - Raw PRG file
    when:
      - event: tag
    depends_on: [test-move-validation, test-comprehensive]
